### ISSUE TITLE
ZeroDivisionError: float division by zero [len(self.used_keys) == 0]

### ISSUE THREAD

**Issue by Agx-1** [allejok96/whackerhero#3]
Hi,

I installed the current release (v0.1.0) and tried converting a MIDI (exported by MuseScore, both export options "expand repetitions" and "export RPNs" were checked) into an mp4 via the GUI. I only filled out the required arguments (midi and dest) and left the rest at its defaults. I got the following stacktrace:

```
Traceback (most recent call last):
  File "C:\Users\censored\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\censored\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\censored\AppData\Local\Programs\Python\Python310\Scripts\whackerhero.exe\__main__.py", line 7, in <module>
  File "C:\Users\censored\AppData\Local\Programs\Python\Python310\lib\site-packages\whackerhero.py", line 483, in gui
    Gooey(
  File "C:\Users\censored\AppData\Local\Programs\Python\Python310\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 134, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "C:\Users\censored\AppData\Local\Programs\Python\Python310\lib\site-packages\whackerhero.py", line 391, in main
    painter = Painter(options.midi, width, height, speed=options.speed, show_text=not options.no_text, masked=masked,
  File "C:\Users\censored\AppData\Local\Programs\Python\Python310\lib\site-packages\whackerhero.py", line 208, in __init__
    self.column_width = (width - width * SIDE_MARGIN * 2) / len(self.used_keys)
ZeroDivisionError: float division by zero
```

Using the cmd leads to the same result:

```
.\whackercmd.exe "D:\Desktop\Noten\BOOMWHACKER\Pop\Midi für Video\Fernando.mid" "D:\Desktop\Noten\BOOMWHACKER\Play along videos\Fernando_test.mp4"
Traceback (most recent call last):
  File "C:\Users\censored\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\censored\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\censored\AppData\Local\Programs\Python\Python310\Scripts\whackercmd.exe\__main__.py", line 7, in <module>
  File "C:\Users\censored\AppData\Local\Programs\Python\Python310\lib\site-packages\whackerhero.py", line 391, in main
    painter = Painter(options.midi, width, height, speed=options.speed, show_text=not options.no_text, masked=masked,
  File "C:\Users\censored\AppData\Local\Programs\Python\Python310\lib\site-packages\whackerhero.py", line 208, in __init__
    self.column_width = (width - width * SIDE_MARGIN * 2) / len(self.used_keys)
ZeroDivisionError: float division by zero
```

Software versions:

- MuseScore 3.6.2.548021803, revision OS: Windows 10 (10.0), Arch.: x86_64, MuseScore version (64-bit): 3.6.2.548021803, revision: github-musescore-musescore-3224f34
- Python 3.10.11 (after I realized that Python 3.11.3 is not supported, tried installing with that version before)

**Comment by Agx-1** [comment]
I opened pull request #4, which should fix this issue (MIDIs exported by MuseScore end notes with the "note_on" message with a velocity of 0 instead of "note_off")

**Comment by Agx-1** [comment]
Thank you for the quick reply! I just tested it, your version works as well. Can you please update the package in the PyPI too?

**Comment by allejok96** [comment]
Good reminder! From now on Github Actions should take care of that.
